# [[pages]]
# name = "Test"
# icon = "ğŸ§ª"
# is_section = true

# [[pages]]
# name = "Fragment"
# icon = "ğŸ§ª"
# path = "streamlit/frag.py"


[[pages]]
name = "Data"
icon = "ğŸ’¾"
is_section = true

[[pages]]
path = "streamlit/customer_import.py"
name = "Customer Import"
icon = "ğŸ‘¦"

[[pages]]
path = "streamlit/supplier_import.py"
name = "Supplier Import"
icon = "ğŸ‘§"

[[pages]]
name = "Reports"
icon = "ğŸ“"
is_section = true

[[pages]]
path = "streamlit/monthly_supplier_report.py"
name = "Monthly Supplier Report"
icon = "ğŸ“ƒ"

[[pages]]
name = "Migration"
icon = "ğŸƒâ€â™‚ï¸â€â¡ï¸"
is_section = true

# [[pages]]
# path = "streamlit/purchase_inv_data_migration.py"
# name = "Purchase Invoice Data Migration"
# icon = "ğŸ’¼"

[[pages]]
path = "streamlit/contra_sql.py"
name = "Make Contra"
icon = "ğŸ’¼"

[[pages]]
path = "streamlit/invoices_sql.py"
name = "Make Purchase/Sales Invoices"
icon = "ğŸ’¼"