[[pages]]
path = "streamlit/monthly_supplier_report.py"
name = "Monthly Supplier Report"
icon = "ğŸ“ƒ"

[[pages]]
path = "streamlit/purchase_inv_data_migration.py"
name = "Purchase Invoice Data Migration"
icon = "ğŸ“ƒ"

[[pages]]
path = "streamlit/customer_import.py"
name = "Customer Import"
icon = "ğŸ™â€â™‚ï¸"

